# Numpy
- NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


## Array
- An Array is a central data structure of the NumPy Library.
- An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element.
- It has a grid of elements that can be indexed in various ways.
- The elements are all of the same type, referred to as the array dtype.
- An array can be indexed by a anpother array, or by intergers.

### rank
- The rank of the arry is the number of dimensions.

### shape
- The shape of the array is a tuple of intergers giving the size of the array along each dimension.

## Vector
- A vector is an arry with a single dimension
(there's no difference between row and column vectors)
- 1-D

In [5]:
import numpy as np
a= np.array([5,5,5,5,5])
a

array([5, 5, 5, 5, 5])

In [19]:
type(a)

numpy.ndarray

### The numpy ndarray class is used to represent both matrices and vectors.

## Matrix
- A matrix refers to an array with two dimensions.
- 2-D

In [21]:
import numpy as np
b = np.array([[5,5,5],[4,4,4],[6,6,6]])
b

array([[5, 5, 5],
       [4, 4, 4],
       [6, 6, 6]])

In [22]:
len(b)

3

In [23]:
b[0]

array([5, 5, 5])

In [24]:
b[0:]

array([[5, 5, 5],
       [4, 4, 4],
       [6, 6, 6]])

In [11]:
print(np.__version__)

1.20.3


In [12]:
# import numpy as np

# arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## 3-D or Higher
- For 3-D or higheer dimensional arrays, the term tensor is also commonly used

##### TensorFlow is a free and open-source software liberary for machine leaning and artificial intelligence

In [25]:
import numpy as np
C = np.array([[5,5,5],[4,4,4]])
C

array([[5, 5, 5],
       [4, 4, 4]])

#### arry attributes:
- Dimensions are called axis
##### 2-axis
- First axis has length=2
- Second axis has length=3

In [6]:
import numpy as np
d = np.array([1,2,3,4,5])
d

array([1, 2, 3, 4, 5])

In [7]:
import numpy as np
e =np.zeros(2)
e

array([0., 0.])

In [8]:
import numpy as np
f =np.ones(2)
f

array([1., 1.])

In [17]:
# Create an empty array with 2 elements
import numpy as np
g =np.empty(2)
g

array([1., 1.])

In [5]:
# with range of elements
import numpy as np
h = np.arange(6)
h

array([0, 1, 2, 3, 4, 5])

In [3]:
# withspecific range of elements
import numpy as np
h = np.arange(2,10)
h

array([2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# Continue..
import numpy as np
h = np.arange(2,10,2)
h

array([2, 4, 6, 8])

In [18]:
# linerly spaced arrays
import numpy as np
k =np.linspace(0,10,num=5) #gives use 5 nums
k

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
# specific data types in array
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [21]:
# specific data types in array
j = np.ones(3, dtype=np.float64)
j

array([1., 1., 1.])

## 2-D arrays

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [27]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3-D array

In [29]:
# making and reshping a 3D arrray
l = np.arange(24).reshape(2,3,4)
l

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])