# numpy practice session

In [1]:
#pip install numpy

In [2]:
# import this library in j.notebook
import numpy as np

## Creating an array using numpy

In [3]:
food =np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [4]:
price =np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(price)

3

In [8]:
len(food)

3

In [9]:
price[2]

5

In [10]:
price[0:]

array([5, 5, 5])

In [11]:
food[1]

'Samosa'

In [12]:
price.mean()

5.0

In [13]:
# Zero
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [18]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# specipic
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [20]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
# table
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [28]:
# line space
np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
# specify your data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [30]:
np.ones(5, dtype=np.float64)

array([1., 1., 1., 1., 1.])

## Array functions

In [31]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10. ])

In [33]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10. ,  12. ,  15. , 100. ,
       320. ])

In [34]:
b =np.array([10.2,3.4,53.6,91.6,45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [35]:
c= np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10. ,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [37]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10. ,  10.2,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

## 2-D arrays

In [45]:
x= np.array([[1,2],[5,4]])
x

array([[1, 2],
       [5, 4]])

In [46]:
y= np.array([[6,7],[8,9]])
y

array([[6, 7],
       [8, 9]])

In [49]:
z = np.concatenate((x,y), axis=0)
z

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [52]:
z = np.concatenate((x,y), axis=1)
z

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

In [54]:
a = np.array([[[0,1,2,3],
               [4,5,6,7]],
              
              [[0,1,2,3],
               [4,5,6,7]],
              
              [[0,1,2,3],
               [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [55]:
# to find the number of dimensions
a.ndim

3

In [57]:
b= np.array([[5,6,7],
            [8,9,10],
            [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [58]:
b.ndim

2

In [60]:
# size (number of elements)
b.size

9

In [61]:
b.shape

(3, 3)

In [62]:
a.size

24

In [63]:
a.shape

(3, 2, 4)

In [69]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
# reshape
b= a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
# reshape
np.reshape(b, newshape=(1,9), order='c')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [77]:
# convert 1D into 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a.shape

(9,)

In [79]:
# row wise
b= a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [80]:
b.shape

(1, 9)

In [81]:
# column wise
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [88]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [85]:
a*10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [87]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [89]:
a.sum()

45

In [90]:
a.mean()

5.0